# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20160512_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallgroup',
            name='bus',
            field=models.CharField(blank=True, choices=[(b'1', b'Bus 1'), (b'2', b'Bus 2'), (b'3', b'Bus 3'), (b'4', b'Bus 4'), (b'5', b'Bus 5'), (b'6', b'Bus 6'), (b'7', b'Bus 7')], max_length=16, verbose_name='Bus'),
        ),
    ]
