# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_add_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallgroup',
            name='structure',
            field=models.CharField(blank=True, choices=[(b'josias', b'Jos\xc3\xadas'), (b'preju', b'Preju'), (b'lared', b'La Red'), (b'g180', b'G180')], max_length=16, verbose_name='Structure'),
        ),
    ]
