# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20150704_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='generation',
            field=models.PositiveIntegerField(choices=[(1, 'Josías 1'), (2, 'Josías 2'), (3, 'Freshmen'), (4, 'Sophomores'), (5, 'Juniors'), (6, 'Seniors'), (7, 'La Red'), (8, 'G180')], verbose_name='Generation'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='structure',
            field=models.CharField(blank=True, choices=[('preju', 'Preju'), ('josias', 'Josías'), ('lared', 'La Red'), ('g180', 'G180')], max_length=16, verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='generation',
            field=models.PositiveIntegerField(choices=[(1, 'Josías 1'), (2, 'Josías 2'), (3, 'Freshmen'), (4, 'Sophomores'), (5, 'Juniors'), (6, 'Seniors'), (7, 'La Red'), (8, 'G180')], verbose_name='Generation'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='structure',
            field=models.CharField(blank=True, choices=[('preju', 'Preju'), ('josias', 'Josías'), ('lared', 'La Red'), ('g180', 'G180')], max_length=16, verbose_name='Structure'),
        ),
    ]
