# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_add_adult_permission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='has_gov_id',
            field=models.BooleanField(default=False, verbose_name='ID on file', help_text='This person has filed a copy of their ID'),
        ),
    ]
