# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_counselor_has_gov_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='cabin',
            field=models.CharField(blank=True, choices=[(b'Sector Norte', ((b'anakaino1', b'Anakaino 1'), (b'anakaino2', b'Anakaino 2'), (b'anakaino3', b'Anakaino 3'), (b'anakaino4', b'Anakaino 4'), (b'koinonia1', b'Koinonia 1'), (b'koinonia2', b'Koinonia 2'), (b'koinonia3', b'Koinonia 3'), (b'koinonia4', b'Koinonia 4'), (b'alfa', b'Alfa'), (b'omega', b'Omega'), (b'oasis', b'Oasis'))), (b'Sector Centro', ((b'agape1', b'\xc3\x81gape 1'), (b'agape2', b'\xc3\x81gape 2'), (b'agape3', b'\xc3\x81gape 3'), (b'agape4', b'\xc3\x81gape 4'), (b'huespedes1', b'Huespedes 1'), (b'huespedes2', b'Huespedes 2'), (b'huespedes3', b'Huespedes 3'), (b'nueva1', b'Nueva 1'), (b'nueva2', b'Nueva 2'), (b'pastoral', b'Pastoral'))), (b'Sector Campo', ((b'moab', b'Moab'), (b'esmirna', b'Esmirna'), (b'efeso', b'\xc3\x89feso'), (b'juda', b'Jud\xc3\xa1'), (b'belen', b'Bel\xc3\xa9n'), (b'sinai', b'Sina\xc3\xad'), (b'gerisim', b'Gerisim'))), (b'Sector Lago', ((b'armenia', b'Armenia'), (b'horeb', b'Horeb'), (b'filadelfia', b'Filadelfia'), (b'ebal', b'Ebal'), (b'peniel', b'Peniel'), (b'moria', b'Moria')))], max_length=16, verbose_name='Cabin'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='cabin',
            field=models.CharField(blank=True, choices=[(b'Sector Norte', ((b'anakaino1', b'Anakaino 1'), (b'anakaino2', b'Anakaino 2'), (b'anakaino3', b'Anakaino 3'), (b'anakaino4', b'Anakaino 4'), (b'koinonia1', b'Koinonia 1'), (b'koinonia2', b'Koinonia 2'), (b'koinonia3', b'Koinonia 3'), (b'koinonia4', b'Koinonia 4'), (b'alfa', b'Alfa'), (b'omega', b'Omega'), (b'oasis', b'Oasis'))), (b'Sector Centro', ((b'agape1', b'\xc3\x81gape 1'), (b'agape2', b'\xc3\x81gape 2'), (b'agape3', b'\xc3\x81gape 3'), (b'agape4', b'\xc3\x81gape 4'), (b'huespedes1', b'Huespedes 1'), (b'huespedes2', b'Huespedes 2'), (b'huespedes3', b'Huespedes 3'), (b'nueva1', b'Nueva 1'), (b'nueva2', b'Nueva 2'), (b'pastoral', b'Pastoral'))), (b'Sector Campo', ((b'moab', b'Moab'), (b'esmirna', b'Esmirna'), (b'efeso', b'\xc3\x89feso'), (b'juda', b'Jud\xc3\xa1'), (b'belen', b'Bel\xc3\xa9n'), (b'sinai', b'Sina\xc3\xad'), (b'gerisim', b'Gerisim'))), (b'Sector Lago', ((b'armenia', b'Armenia'), (b'horeb', b'Horeb'), (b'filadelfia', b'Filadelfia'), (b'ebal', b'Ebal'), (b'peniel', b'Peniel'), (b'moria', b'Moria')))], max_length=16, verbose_name='Cabin'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='cabin',
            field=models.CharField(blank=True, choices=[(b'Sector Norte', ((b'anakaino1', b'Anakaino 1'), (b'anakaino2', b'Anakaino 2'), (b'anakaino3', b'Anakaino 3'), (b'anakaino4', b'Anakaino 4'), (b'koinonia1', b'Koinonia 1'), (b'koinonia2', b'Koinonia 2'), (b'koinonia3', b'Koinonia 3'), (b'koinonia4', b'Koinonia 4'), (b'alfa', b'Alfa'), (b'omega', b'Omega'), (b'oasis', b'Oasis'))), (b'Sector Centro', ((b'agape1', b'\xc3\x81gape 1'), (b'agape2', b'\xc3\x81gape 2'), (b'agape3', b'\xc3\x81gape 3'), (b'agape4', b'\xc3\x81gape 4'), (b'huespedes1', b'Huespedes 1'), (b'huespedes2', b'Huespedes 2'), (b'huespedes3', b'Huespedes 3'), (b'nueva1', b'Nueva 1'), (b'nueva2', b'Nueva 2'), (b'pastoral', b'Pastoral'))), (b'Sector Campo', ((b'moab', b'Moab'), (b'esmirna', b'Esmirna'), (b'efeso', b'\xc3\x89feso'), (b'juda', b'Jud\xc3\xa1'), (b'belen', b'Bel\xc3\xa9n'), (b'sinai', b'Sina\xc3\xad'), (b'gerisim', b'Gerisim'))), (b'Sector Lago', ((b'armenia', b'Armenia'), (b'horeb', b'Horeb'), (b'filadelfia', b'Filadelfia'), (b'ebal', b'Ebal'), (b'peniel', b'Peniel'), (b'moria', b'Moria')))], max_length=16, verbose_name='Cabin'),
        ),
    ]
