# Generated by Django 1.10.7 on 2017-06-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("signup", "0017_updated_cabins"),
    ]

    operations = [
        migrations.AddField(
            model_name="camper",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counselor",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guest",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parent",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="site",
            ),
            preserve_default=False,
        ),
    ]
