# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_add_site_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'verbose_name': 'Camp', 'verbose_name_plural': 'Camp'},
        ),
    ]
