# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 04:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_auto_20170702_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="site",
            ),
        ),
    ]
