# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0008_auto_20170716_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="fine",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Fine"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="permission_location",
            field=models.CharField(
                help_text="The location where the permission are signed",
                max_length=75,
                null=True,
                verbose_name="Permission location",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="permission_timestamp",
            field=models.DateTimeField(
                help_text="The date and time when the permissions are signed",
                null=True,
                verbose_name="Permission timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="signup_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Signup fee"
            ),
        ),
    ]
