# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-10 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_camp_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="permission_location",
            field=models.CharField(
                default="",
                help_text="The location where the permission are signed",
                max_length=75,
                verbose_name="Permission location",
            ),
            preserve_default=False,
        ),
    ]
