name: lint-and-deploy

on: [push]

jobs:

  # Backend code quality
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.4
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.6
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Lint
        run: |
          source .venv/bin/activate
          flake8 .
          black . --check
          isort . --check-only
      - name: Test
        env:
          DEBUG: true
          DATABASE_URL: psql://postgres:postgres@127.0.0.1:5432/test_db
          SECRET_KEY: abc123
          ALLOWED_HOSTS: localhost,127.0.0.1
        run: |
          source .venv/bin/activate
          pytest

  # Deploy
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ secrets.DOKKU_APP }}
          git-push-flags: '--force'
